Fix CSC : error CS9057: The analyzer assembly 'C:\Users\runneradmin\.nuget\packages\microsoft.codeanalysis.csharp.codestyle\4.6.0\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CodeStyle.dll' references version '4.6.0.0' of the compiler, which is newer than the currently running version '4.4.0.0'.